FROM node:18-alpine AS builder
ENV ORIGIN=http://localhost:3000
ARG SUPABASE_URL_PARAM
ARG SUPABASE_ANON_KEY_PARAM
ARG CRYPTER_KEY_PARAM
ARG PUBLIC_SUPABASE_URL_PARAM
ARG PUBLIC_SUPABASE_ANON_KEY_PARAM
ARG RESEND_KEY_PARAM
ENV SUPABASE_URL=$SUPABASE_URL_PARAM
ENV SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY_PARAM
ENV CRYPTER_KEY=$CRYPTER_KEY_PARAM
ENV PUBLIC_SUPABASE_URL=$PUBLIC_SUPABASE_URL_PARAM
ENV PUBLIC_SUPABASE_ANON_KEY=$PUBLIC_SUPABASE_ANON_KEY_PARAM
ENV RESEND_KEY=$RESEND_KEY_PARAM
RUN echo $SUPABASE_URL
RUN echo $SUPABASE_ANON_KEY
RUN echo $CRYPTER_KEY
RUN echo $PUBLIC_SUPABASE_URL
RUN echo $PUBLIC_SUPABASE_ANON_KEY
RUN echo $RESEND_KEY_PARAM
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
RUN npm prune --production

FROM node:18-alpine

EXPOSE 3000
ENV NODE_ENV=development
ENV ORIGIN=http://localhost:3000
ARG SUPABASE_URL_PARAM
ARG SUPABASE_ANON_KEY_PARAM
ARG CRYPTER_KEY_PARAM
ARG PUBLIC_SUPABASE_URL_PARAM
ARG PUBLIC_SUPABASE_ANON_KEY_PARAM
ARG RESEND_KEY_PARAM
ENV SUPABASE_URL=$SUPABASE_URL_PARAM
ENV SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY_PARAM
ENV CRYPTER_KEY=$CRYPTER_KEY_PARAM
ENV PUBLIC_SUPABASE_URL=$PUBLIC_SUPABASE_URL_PARAM
ENV PUBLIC_SUPABASE_ANON_KEY=$PUBLIC_SUPABASE_ANON_KEY_PARAM
ENV RESEND_KEY=$RESEND_KEY_PARAM
RUN echo $SUPABASE_URL
RUN echo $SUPABASE_ANON_KEY
RUN echo $CRYPTER_KEY
RUN echo $PUBLIC_SUPABASE_URL
RUN echo $PUBLIC_SUPABASE_ANON_KEY
RUN echo $RESEND_KEY_PARAM
WORKDIR /app
COPY --from=builder /app/src /app/src
COPY --from=builder /app/build ./
COPY --from=builder /app/node_modules node_modules/
COPY package.json ./

CMD [ "node", "./index.js" ]